name = "bkash-sync-cloudflare-server"
main = "src/index.ts"
compatibility_date = "2026-05-25"

# Environment Variables
[vars]
# Note: You can define non-sensitive keys here, but set your ADMIN_API_KEY as a "secret" instead 
# (via `wrangler secret put ADMIN_API_KEY` on production)

# Binding the Cloudflare D1 SQL Database to our Worker environment
[[d1_databases]]
binding = "DB"                          # Used in code as env.DB
database_name = "bkash-sync-db"         # Your D1 database name in Cloudflare
database_id = "xxxxxxxx"     # Replace with your actual created D1 database UUID